name: Test CI

on:
  push:
    branches:
      - main

jobs:
  test:
    name: test speed
    runs-on: ubuntu-latest  

    container:
      image: catthehacker/ubuntu:act-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run script in Docker container
      run: |
        docker run -v $PWD:/app git.mamahaha.work/sangge/tpre:base ls
        docker run -v $PWD:/app git.mamahaha.work/sangge/tpre:base python speed_test.py
