name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Web Server
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3


    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.4
      with:
        host: "110.41.155.96,110.41.130.197,110.41.21.35"
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "src/server.py,src/client.py,src/node.py"
        target: "/root/mimajingsai/src/"          


      
