name: Test CI

on:
  push:
    branches:
      - main

jobs:
  test:
    name: test speed
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker container
      uses: addnab/docker-run-action@v3
      with:
        image: git.mamahaha.work/sangge/tpre:base
        options: -v .:/app  # 将当前工作目录挂载到容器中
        run: |
          python speed_test.py  # 执行Python脚本
