name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Web Server
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3


    - name: copy file via ssh password
      uses: cross-the-world/scp-pipeline@master
      with:
        host: "110.41.155.96"
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}
        local: "src/*"
        remote: /root/mimajingsai/src/   

    - name: copy file via ssh password
      uses: cross-the-world/scp-pipeline@master
      with:
        host: "110.41.130.197"
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}
        local: "src/*"
        remote: /root/mimajingsai/src/ 

    - name: copy file via ssh password
      uses: cross-the-world/scp-pipeline@master
      with:
        host: "110.41.21.35"
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}
        local: "src/*"
        remote: /root/mimajingsai/src/ 


      
